=== BackInBash/Schulaufgaben/xml/klasse.dtd
<?xml version="1.0"?>
<!DOCTYPE klasse [
	<!ELEMENT klasse (name, klasse, beruf, noten)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT klasse (#PCDATA)>
		<!ELEMENT beruf (#PCDATA)>
<!DOCTYPE noten [
	<!ELEMENT noten (ITS, SAE)>
		<!ELEMENT ITS (#PCDATA)>
		<!ELEMENT SAE (#PCDATA)>
	]>
]>

=== BackInBash/Schulaufgaben/xml/Klasse.xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE klasse SYSTEM "Klasse.dtd">
<!-- Willkommen in der Klasse XML -->
<klasse>
	<schüler>
		<name></name>
		<klasse></klasse>
		<beruf></beruf>
		<noten>
			<ITS></ITS>
			<SAE></SAE>
		</noten>
	</schüler>
</klasse>
